## Loading datasets

In [1]:
import pandas as pd

In [3]:
service_train = pd.read_csv("ServiceTrain.csv")

In [4]:
service_train

OilQual  EnginePerf  NormMileage    TyreWear    HVACwear Service
0    103.388821  103.504032   103.051485  106.172658  105.686843      No
1     26.765516   26.188265    31.259536   29.186162   31.311275     Yes
2     62.413282   63.681061    59.720883   64.704031   58.620518     Yes
3     45.533338   49.906615    48.777581   48.113851   47.952072      No
4    104.388821  103.284032   103.051485  105.822658  106.536843      No
..          ...         ...          ...         ...         ...     ...
310  105.168821  103.744032   103.051485  107.172658  104.856843      No
311  104.388821  105.744032   103.051485  105.782658  104.196843      No
312   63.823282   62.741061    59.720883   61.654031   62.620518     Yes
313   26.535516   27.418265    31.259536   27.486162   33.311275     Yes
314   26.215516   26.338265    31.259536   27.036162   31.311275     Yes

[315 rows x 6 columns]

In [5]:
service_test = pd.read_csv("ServiceTest.csv")

In [6]:
service_test

OilQual  EnginePerf  NormMileage    TyreWear    HVACwear Service
0     45.773338   49.936615    49.777581   48.263851   50.952072      No
1      4.987185    7.891003     6.588986    9.493161    3.240262      No
2      4.987185    4.891003     7.308986    8.373161    2.780262      No
3    106.388821  104.454032   103.051485  106.282658  105.536843      No
4    104.388821  103.744032   103.051485  106.132658  105.776843      No
..          ...         ...          ...         ...         ...     ...
130  103.388821  103.934032   102.941485  106.172658  105.536843      No
131    5.987185    6.081003     6.588986    8.373161    0.370262      No
132   25.385516   27.418265    32.309536   30.036162   31.311275     Yes
133   45.533338   49.666615    49.347581   51.263851   47.922072      No
134  104.388821  104.504032   102.461485  106.172658  105.536843      No

[135 rows x 6 columns]

In [7]:
service_train.isnull().sum()

OilQual        0
EnginePerf     0
NormMileage    0
TyreWear       0
HVACwear       0
Service        0
dtype: int64

In [8]:
service_test.isnull().sum()

OilQual        0
EnginePerf     0
NormMileage    0
TyreWear       0
HVACwear       0
Service        0
dtype: int64

In [9]:
service_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OilQual      135 non-null    float64
 1   EnginePerf   135 non-null    float64
 2   NormMileage  135 non-null    float64
 3   TyreWear     135 non-null    float64
 4   HVACwear     135 non-null    float64
 5   Service      135 non-null    object 
dtypes: float64(5), object(1)
memory usage: 6.5+ KB


In [10]:
service_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OilQual      315 non-null    float64
 1   EnginePerf   315 non-null    float64
 2   NormMileage  315 non-null    float64
 3   TyreWear     315 non-null    float64
 4   HVACwear     315 non-null    float64
 5   Service      315 non-null    object 
dtypes: float64(5), object(1)
memory usage: 14.9+ KB


##Replacing Service values

In [13]:
service_train.Service = service_train.Service.replace("Yes", 1)
service_train.Service = service_train.Service.replace("No", 0)
service_test.Service = service_test.Service.replace("Yes", 1)
service_test.Service = service_test.Service.replace("No", 0)

In [14]:
service_train.Service

0      0
1      1
2      1
3      0
4      0
      ..
310    0
311    0
312    1
313    1
314    1
Name: Service, Length: 315, dtype: int64

## Splitting train test

In [15]:
x_train, y_train = service_train.iloc[:, :-1], service_train.Service

In [16]:
x_train, y_train

(        OilQual  EnginePerf  NormMileage    TyreWear    HVACwear
 0    103.388821  103.504032   103.051485  106.172658  105.686843
 1     26.765516   26.188265    31.259536   29.186162   31.311275
 2     62.413282   63.681061    59.720883   64.704031   58.620518
 3     45.533338   49.906615    48.777581   48.113851   47.952072
 4    104.388821  103.284032   103.051485  105.822658  106.536843
 ..          ...         ...          ...         ...         ...
 310  105.168821  103.744032   103.051485  107.172658  104.856843
 311  104.388821  105.744032   103.051485  105.782658  104.196843
 312   63.823282   62.741061    59.720883   61.654031   62.620518
 313   26.535516   27.418265    31.259536   27.486162   33.311275
 314   26.215516   26.338265    31.259536   27.036162   31.311275
 
 [315 rows x 5 columns],
 0      0
 1      1
 2      1
 3      0
 4      0
       ..
 310    0
 311    0
 312    1
 313    1
 314    1
 Name: Service, Length: 315, dtype: int64)

In [17]:
x_test, y_test = service_test.iloc[:, :-1], service_test.Service

## Logistic Regression

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [24]:
lr = LogisticRegression()

In [25]:
lr.fit(x_train, y_train)

LogisticRegression()

In [26]:
prediction = lr.predict(x_test)

In [27]:
prediction

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0])

In [28]:
confusion_matrix(y_test, prediction)

array([[94,  5],
       [ 7, 29]])

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(y_test, prediction)

0.9111111111111111

In [31]:
service_train.corr()

OilQual  EnginePerf  NormMileage  TyreWear  HVACwear   Service
OilQual      1.000000    0.998271     0.997599  0.999045  0.997717 -0.192112
EnginePerf   0.998271    1.000000     0.998385  0.998228  0.998077 -0.202400
NormMileage  0.997599    0.998385     1.000000  0.997837  0.998400 -0.208413
TyreWear     0.999045    0.998228     0.997837  1.000000  0.997176 -0.208819
HVACwear     0.997717    0.998077     0.998400  0.997176  1.000000 -0.169171
Service     -0.192112   -0.202400    -0.208413 -0.208819 -0.169171  1.000000

## GHI report

In [32]:
report_data = pd.read_csv("report.csv")

In [33]:
report_data

Economy      Fam   Health  Freedom  H_Score
0    1.39651  1.34951  0.94143  0.66557    7.587
1    1.30232  1.40223  0.94784  0.62877    7.561
2    1.32548  1.36058  0.87464  0.64938    7.527
3    1.45900  1.33095  0.88521  0.66973    7.522
4    1.32629  1.32261  0.90563  0.63297    7.427
..       ...      ...      ...      ...      ...
153  0.22208  0.77370  0.42864  0.59201    3.465
154  0.28665  0.35386  0.31910  0.48450    3.340
155  0.66320  0.47489  0.72193  0.15684    3.006
156  0.01530  0.41587  0.22396  0.11850    2.905
157  0.20868  0.13995  0.28443  0.36453    2.839

[158 rows x 5 columns]

In [35]:
x, y = report_data.iloc[:, :-1], report_data.H_Score

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.25, random_state= 1)

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
model = LinearRegression()

In [40]:
model.fit(x_train, y_train)

LinearRegression()

In [43]:
prediction = model.predict(x_test)

In [44]:
prediction

array([6.11316062, 4.77796498, 6.656147  , 5.54261062, 4.73310381,
       6.62057523, 5.56466379, 6.35588816, 6.20256146, 4.86185431,
       4.71124091, 5.40264118, 4.08050753, 5.17955749, 5.91616396,
       5.65626224, 5.60328872, 5.98497161, 5.0000874 , 4.48712066,
       6.35015372, 6.53411665, 4.11063837, 6.83199389, 4.71244943,
       6.32837849, 6.93858853, 5.58431714, 3.96643686, 4.72975662,
       4.60116937, 2.9156228 , 4.33440209, 6.0482583 , 5.30466335,
       5.40911744, 4.54098749, 5.88485657, 6.1823391 , 3.29670127])

In [45]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [46]:
mse = mean_squared_error(y_test, prediction)

In [47]:
mse

0.20985931508432856

In [48]:
np.sqrt(mse)

0.4581040439510751

In [49]:
5.2*30

156.0